name: make-master

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build
        run: make build
